### ISSUE TITLE
Ошибка в условии задания

### ISSUE THREAD

**Issue by nanshakov** [bitgorbovsky/erlang-course-tasks#4]
В пункте "Напишите функцию, которая по списку вложенных списков строит линейный список. Пример: flatten([[1, [2 , [3] , [] ], [[[4]]], [5,6]]) => [1,2,3,4,5,6].. Подсказка: воспользуйтесь функцией concatenate." выражение [[1, [2 , [3] , [] ], [[[4]]], [5,6]] имеет число открывающихся скобок большее, чем закрыто.

**Comment by bitgorbovsky** [comment]
Спасибо! Исправил
